from pygame.locals import *

ALTS = ((K_v, '√'),
        (K_p, 'π'),
        (K_t, '±'),
        (K_EQUALS, '≠'))
SHIFTS = ((K_5, "%"),
          (K_6, "^"),
          (K_8, '*'),
          (K_9, '('),
          (K_0, ')'),
          (K_EQUALS, '+'),
          (K_COMMA, '<'),
          (K_PERIOD, '>'),
          (K_a, 'A'),
          (K_b, 'B'),
          (K_c, 'C'),
          (K_d, 'D'),
          (K_e, 'E'),
          (K_f, 'F'),
          (K_g, 'G'),
          (K_h, 'H'),
          (K_i, 'I'),
          (K_j, 'J'),
          (K_k, 'K'),
          (K_l, 'L'),
          (K_m, 'M'),
          (K_n, 'N'),
          (K_o, 'O'),
          (K_p, 'P'),
          (K_q, 'Q'),
          (K_r, 'R'),
          (K_s, 'S'),
          (K_t, 'T'),
          (K_u, 'U'),
          (K_v, 'V'),
          (K_w, 'W'),
          (K_x, 'X'),
          (K_y, 'Y'),
          (K_z, 'Z'),
          (K_MINUS, '_'))
SWITCH = (('√', "sqrt"),
          ('^', "**"),
          ('%', "*0.01"),
          ('π', "pi"),
          ("+-", '±'),
          #   ('=', "=="),
          ('≠', "!="))
