name: Release

# on:
#   push:
#     branches: [ master ]

on: push

jobs:
  build:
    name: "Build and Release"
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-experimental"
        title: "Release"
        prerelease: true
        files: |
          linux.zip
          mac.zip
          windows.zip